name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5

    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - run: sudo apt install -y binaryen
    - run: trunk build --release
    
    - uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: ${{ secrets.DESTINATION }}
        rm: true