name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Swatinem/rust-cache@v2

    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install trunk
    - run: trunk build --release
    
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: ${{ secrets.DESTINATION }}
        rm: true